root: true
parser: "@typescript-eslint/parser"
parserOptions:
  project: true
extends:
  - eslint:recommended
  - plugin:@typescript-eslint/strict-type-checked
  - plugin:@typescript-eslint/stylistic-type-checked
  - plugin:playwright/recommended
  - plugin:prettier/recommended
  - plugin:deprecation/recommended
  - plugin:perfectionist/recommended-natural-legacy
plugins:
  - unused-imports
rules:
  playwright/expect-expect: off
  no-unused-vars: off
  unused-imports/no-unused-imports: error
  unused-imports/no-unused-vars: error
  "@typescript-eslint/consistent-type-definitions": off
  "@typescript-eslint/no-non-null-assertion": off
  "@typescript-eslint/restrict-template-expressions": off
  "@typescript-eslint/no-unused-expressions": off
  "playwright/max-nested-describe": ["error", { "max": 6 }]
